version: '3.8'

services:
  wazuh:
    image: wazuh/wazuh:4.9.2
    container_name: wazuh-manager
    hostname: wazuh-manager
    volumes:
      - wazuh_data:/var/ossec/data
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    networks:
      - wazuh-network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    ports:
      - "9200:9200"
    networks:
      - wazuh-network
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch
      - wazuh
    networks:
      - wazuh-network
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - wazuh-network
    restart: always

volumes:
  wazuh_data:
  elasticsearch_data:

networks:
  wazuh-network:
    driver: bridge
